### ISSUE TITLE
Website Build is still Failing to display translated Portions

### ISSUE THREAD

**Issue by milotype** [gaphor/gaphor.github.io#116]
The website is still failing to display all translated text.
See screenshots below, or switch the language of the website (for intance into Croatian) to see untranslated texts.

## 1. https://gaphor.org/hr/#about
  ![about](https://user-images.githubusercontent.com/43657314/232031664-0c4cd4e1-a8e7-4e8f-b3ea-7b16aba7ad5a.png)

## 2. https://gaphor.org/hr/download
  ![download](https://user-images.githubusercontent.com/43657314/232031833-ede855da-a495-4db5-bfb0-76f64e33aef7.png)

## 3. https://gaphor.org/hr/tutorials
  ![tutorials](https://user-images.githubusercontent.com/43657314/232031896-7d42b80c-53cb-4a2a-9f43-7d535772a7a2.png)

## 4. https://gaphor.org/hr/discuss
  ![discuss](https://user-images.githubusercontent.com/43657314/232032008-0a305d56-69ee-449a-81c6-017fcabdea51.png)

## 5. https://gaphor.org/hr/contribute
  ![contribute](https://user-images.githubusercontent.com/43657314/232032085-d56e13bc-b6f3-4d85-abfe-5af0232182e5.png)

**Comment by danyeaw** [comment]
Thanks @milotype for reporting this! It looks like some of the pages are failing to translate now, I'll take a look.

**Comment by danyeaw** [comment]
The filters of html and Markdown urls was causing the po4a to fail to translate portions of the pages with those things. The negative of this is that there is more of those things in the translation strings. Over time, we could look at trying to reduce this by using liquid tags or classes in Markdown.

This should be fixed by 5c41b9d8603ff7c98e7d47bc71691a82b7cb981a, could you please verify?

**Comment by milotype** [comment]
@danyeaw There are still some untranslated parts:

## 1. https://gaphor.org/hr/#about
![multiplatform](https://user-images.githubusercontent.com/43657314/232315752-d956eeb7-36a9-4b1f-9ba2-e7bdc52d147d.png)

## 2. https://gaphor.org/hr/download
![download](https://user-images.githubusercontent.com/43657314/232314632-eb40b692-2baf-4994-9d36-e46ace6a599f.png)

## 3. https://gaphor.org/hr/tutorials
![tutorials](https://user-images.githubusercontent.com/43657314/232315437-9d85ea5b-c987-4ef8-93c6-76c85d4658bf.png)

## 4. https://gaphor.org/hr/discuss
![get-in-touch](https://user-images.githubusercontent.com/43657314/232315577-92e382bd-1528-412f-9f15-ad9f6575600e.png)

## 5. https://gaphor.org/hr/contribute
![contribute](https://user-images.githubusercontent.com/43657314/232315684-6db62f53-e8d9-413f-8aaa-f4e862ae965c.png)

**Comment by danyeaw** [comment]
Hi @milotype, you need to translate those strings:

https://github.com/gaphor/gaphor.github.io/blob/main/po/site.hr.po#L445
https://github.com/gaphor/gaphor.github.io/blob/main/po/site.hr.po#L52

etc.

There are 26 untranslated strings for the Croation translation:
https://hosted.weblate.org/translate/gaphor/gaphor-github-io/hr/?q=state:%3Ctranslated

I also saw that Weblate was still locked, the translation components should be unlocked now.

**Comment by milotype** [comment]
Hi @danyeaw, I've solved all ov the above mentioned stuff.

But the https://hosted.weblate.org/projects/gaphor/docs-gaphor-org/hr/ is still locked.

**Comment by danyeaw** [comment]
Should be unlocked now.
