### ISSUE TITLE
Please allow at https://gaphor.org/hu/ the following to be translatable

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#127]
Please allow at https://gaphor.org/hu/ the following to be translatable:
1. `Build Class, Interaction, and State Machine diagrams for software or Block Definition and Requirements diagrams for systems. Model the elements you need. If you want to mix and match, you can even add different diagram items to the same diagram to get the view you need.`
2. `Customize the diagrams you create with our built-in styling engine.`
3. `Easily find all element of your model in the tree view.`
4. `Love dark mode? We can do that too.`
5. `There are many ways to install Gaphor. The simplest is to download the official installer for Windows or macOS. For Linux you can install Gaphor using FlatHub. You can also use Python’s built-in pip tool as long as you have all the required dependencies installed.`
6. `Blog and News`
7. `[Contact the team](https://gaphor.org/hu/discuss) if you want to share content related to Gaphor.`
8. `We love to hear from you`
9. `[Open an issue on GitHub](https://github.com/gaphor/gaphor/issues)`
10. `[Tech docs](https://docs.gaphor.org/en/latest)`
11. `Theme:`

Thank you

**Comment by ovari** [comment]
12. `Gaphor works on all major platforms: [Windows](https://gaphor.org/hu/download#windows), [Macos](https://gaphor.org/hu/download#macos), and [Linux](https://gaphor.org/hu/download#linux).`
13. `No vendor lock-in: Gaphor is written in Python and is 100% Open Source, available under a friendly [Apache 2 license](https://github.com/gaphor/gaphor/blob/main/LICENSE.txt).`
14. `Whether you’re a casual modeler documenting a project or a Model Driven Development expert, Gaphor has got you covered.`
15. `UML is a graphical modeling language, so all information you put in the model is visible in the diagrams. For example, stereotypes are modeled in diagrams. No hidden panels and property pages. Just diagrams!`
16. `Gaphor is extensible. Plug-in a code generator or export your diagrams for documentation. Create your own extensions and access them through the GUI or CLI.`
17. `Gaphor implements the UML, SysML, and RAAML OMG standards. It also includes support for the C4 model for visualizing software architectures.`

**Comment by danyeaw** [comment]
Hi @ovari, all of those strings are translatable here:
https://hosted.weblate.org/projects/gaphor/gaphor-org-strings/hu/ and https://hosted.weblate.org/projects/gaphor/gaphor-github-io/hu/

**Comment by ovari** [comment]
11. `Theme` No strings found!
https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?q=Theme&sort_by=-priority%2Cposition&checksum=

**Comment by ovari** [comment]
9. `[Open an issue on GitHub](https://github.com/gaphor/gaphor/issues)` No strings found!
https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?q=Open+an+issue+on+GitHub&sort_by=-priority%2Cposition&checksum=

**Comment by ovari** [comment]
8. `We love to hear from you` _No strings found!_
https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?q=We+love+to+hear+from+you&sort_by=-priority%2Cposition&checksum=

**Comment by ovari** [comment]
@danyeaw all strings should be updated. Thanks for your prompt response.
