### ISSUE TITLE
Add German to the language dropdown list

### ISSUE THREAD

**Issue by milotype** [gaphor/gaphor.github.io#135]
The Gaphor app is translated into German.
The website isn't translated completely yet.
Nevertheless, please enable switching to German translation in the language dropdown menu by adding `"de": "Deutsch"` to the `_data/languagenames.json` file.

**Comment by danyeaw** [comment]
Thanks @milotype, closed by [24009ca](https://github.com/gaphor/gaphor.github.io/commit/24009ca3942fe1de24bcc728b383731016545bee)
