### ISSUE TITLE
Please allow https://gaphor.org/hu/download/ to be completely translatable

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#140]
Please allow https://gaphor.org/hu/download/ to be completely translatable.

![image](https://user-images.githubusercontent.com/17465872/235787860-10d6e143-3bdc-460b-b2cc-efb0f524c303.png)

Thank you

**Comment by danyeaw** [comment]
Thanks @ovari! Fixed by https://github.com/gaphor/gaphor.github.io/commit/4d2bc076deba8668083f5a63ed3dba32fd6c4174

**Comment by ovari** [comment]
At https://gaphor.org/hu/blog/, please allow the following to be translatable:
1. `Read more`
2. `By Arjan Molenaar on February 25, 2023`

![image](https://user-images.githubusercontent.com/17465872/236703681-0e2d4a26-bd90-47c7-a3a5-419239a70380.png)

Thank you

**Comment by danyeaw** [comment]
I fixed this, you should now be able to translate those. I also changed the date to ISO 8601 format.

**Comment by ovari** [comment]
Is `on` translatable?

Should the string be translatable?

`By %1 on %2`?

**Comment by ovari** [comment]
`By %1 (%2)`

where %1 = author, %2 = date

**Comment by danyeaw** [comment]
Ok, on is now translatable as well :+1:

**Comment by ovari** [comment]
> Ok, on is now translatable as well

May be hard to translate the sentence as translator may not know that `on` refers to a date?

Could the string have `on` removed to become:
`By %1 (%2)`

What do you think?

Thank you

**Comment by ovari** [comment]
`on` in Hungarian is added after the date and changes. For example it could be `-án` or `-én`.

Removing `on` and having the date in brackets `(...)` would solve this situation.

Thank you

**Comment by ovari** [comment]
`English` -> `Hungarian`
`on 8 May 2023` -> `2023. május 8-án`
`on 9 May 2023` -> `2023. május 9-én`

`on` at the beginning -> `-án` or `-én` at the end

**Comment by danyeaw** [comment]
Ok, moved the date to parenthesis.
