### ISSUE TITLE
Website again failing to display translated web pages

### ISSUE THREAD

**Issue by milotype** [gaphor/gaphor.github.io#179]
Please check why the website/web pages again don't translate.

Take a look at https://gaphor.org/hr/ and the other pages in the navigation menu [Informacije](https://gaphor.org/hr/#about) [Preuzmi](https://gaphor.org/hr/download) [Vježbe](https://gaphor.org/hr/tutorials) [Blog](https://gaphor.org/hr/blog) [Kontaktiraj zajednicu](https://gaphor.org/hr/discuss) [Doprinesi](https://gaphor.org/hr/contribute)

The pages don't display the Croatian translations. It doesn't work in any language!
There was a similar problem before: issue #116, but now it's even worse :-( The individual web pages are entirely untranslated!

**Comment by danyeaw** [comment]
Hi @milotype, thanks for the issue report. I did rebuild the translations and push them just now. It looks like this area of the homepage isn't showing translations:
![image](https://github.com/gaphor/gaphor.github.io/assets/10014976/16650ead-6c74-4ed6-ae81-764cfc265596)

Are there other issues?

**Comment by milotype** [comment]
Hi @danyeaw. Here's a recap of the problems:

1. The area you mentioned above isn't showing translations. This should be corrected/translations implemented.
2. The title "Modeling for Everyone" on the homepage does not translate in any language.

![Title](https://github.com/gaphor/gaphor.github.io/assets/43657314/5e7b8f0d-b532-4f0c-a8ae-9553101cf683)

3. There are still problems with localized pages. All localized links, except the link "About" (*see comment at the end), in the menu open the correct pages/URLs, but the pages themselves **show only English text**. Example for Croatian: 
- Open "https://gaphor.org/" in the browser.
- Switch the Language to Croatian. 
- Pressing the link "Preuzmi" (engl. Download) in the menu, a page with the address "https://gaphor.org/hr/download/" opens, but shows the whole content in English. This also happens when pressing the links for the different platforms in the "Download" section of the homepage.

![Download page](https://github.com/gaphor/gaphor.github.io/assets/43657314/c040656b-ac3c-4f98-af25-c271393951f9)

*The link to "About" works because it does not open an new page, but rather moves down to that section on the homepage.

**Comment by danyeaw** [comment]
Hi @milotype, it looks like a couple of the translations had the wrong links, which was causing the website build to fail. I corrected this in d73046e. Do you want to check that everything looks good now?

**Comment by milotype** [comment]
@danyeaw, I confirm that the translations work now! :-)
