### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#35]
Can the [Gaphor website](https://gaphor.org/) please be translatable?

The website translation could be available as a new component at the [Gaphor Project on Weblate](https://hosted.weblate.org/projects/gaphor/). [Plots](https://hosted.weblate.org/projects/plots/) and [JASP](https://hosted.weblate.org/projects/jasp/) have multiple components.

You could then have a website with multiple languages, like:
1. Thunderbird
* https://www.thunderbird.net/en-US/
* https://www.thunderbird.net/hu/
2. Jami
* https://jami.net/?lang=en
* https://jami.net/?lang=hu

What do you think?

Thank you

**Comment by danyeaw** [comment]
Maybe we could use the [jekyll multiple languages plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin) to accomplish this.

@amolenaar Does this sound like a good approach to you? If so, I could work on a PR.

**Comment by amolenaar** [comment]
We can only use a few plugins for Github Pages. However it seems to be possible to use it. The multilingual plugin looks okay.

**Comment by danyeaw** [comment]
I looked into this more, and the Jekyll multiple language plugin isn't supported by GitHub Pages. Weblate does support direct translation of HTML and Javascript using the [Weblate CDN](https://docs.weblate.org/en/latest/devel/html.html#). I started to try to set this up and Weblate even pushed a mostly empty commit, but this is still some work to do here.

**Comment by milotype** [comment]
@danyeaw I do not undertand, why you use so many `/n` (new lines/break lines) and indentations with space characters in your strings for _Gaphor/gaphor.github.io_ on **Weblate**.

For instance in the key: [1c211250062e8749](https://hosted.weblate.org/translate/gaphor/gaphor-github-io/en/?checksum=d325bdf34df041cd&sort_by=-priority,position)

Unless necessary, I'd suggest to remove them all in all strings.

**Comment by danyeaw** [comment]
Closed by #41. @ovari and @milotype, the website is now available to be translated in Hungarian and Croatian on Weblate :+1:

**Comment by ovari** [comment]
1. The `Learn more` and `Download` buttons on the main webpage don't seem to be translatable as they are not . Can you please fix?
2. Do translations automatically appear? If so, how long does it take? If not, what need to happen?

Thank you

**Comment by ovari** [comment]
Please see https://github.com/gaphor/gaphor.github.io/issues/35#issuecomment-1085666370 on the GitHub website as it has been edited many times. Thank you

**Comment by danyeaw** [comment]
@ovari Can you please open a new issue?

**Comment by ovari** [comment]
@danyeaw done #53, #54, #55, #56, #57, #58, #59, and #60.

**Comment by milotype** [comment]
@danyeaw 
Croatian translations (app and website) are now complete at Weblate!
