### ISSUE TITLE
Blurry image at non-English website

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#54]
The image is blurry at https://gaphor.org/hr/ and https://gaphor.org/hu/. The image is clear at https://gaphor.org/.

![image](https://user-images.githubusercontent.com/17465872/161379709-ebea0bfc-4dd9-45d6-9fe3-c0e4e2087c79.png)

Thank you

**Comment by danyeaw** [comment]
Fixed by 8d2d923d6619c622b74e46f1271359adc5b65b73.
