### ISSUE TITLE
Enable translation of Learn more and Download buttons

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#55]
Please enable the buttons on the main webpage to be translatable.

1. [Learn more](https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?offset=1&q=Learn+more&sort_by=-priority%2Cposition&checksum=) button on the main webpage
1. [Download](https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?offset=1&q=Download&sort_by=-priority%2Cposition&checksum=) button on the main webpage

![image](https://user-images.githubusercontent.com/17465872/161379827-56d21cc1-6f27-4fef-bfec-72b8df5b42ab.png)

Thank you

**Comment by danyeaw** [comment]
Closed by a66407be99ece6ac9202de8d51ee34efed0f3f75.
