### ISSUE TITLE
Enable translation of navigation

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#56]
Please enable top row strings to be translatable.

1. [About](https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?offset=1&q=About&sort_by=-priority%2Cposition&checksum=) top row string
1. [Download](https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?offset=1&q=Download&sort_by=-priority%2Cposition&checksum=) top row string
1. [Blog](https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?offset=1&q=blog&sort_by=-priority%2Cposition&checksum=) top row string
1. [GitHub repository](https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?offset=1&q=GitHub+repository&sort_by=-priority%2Cposition&checksum=) top row popout string
1. Perhaps all the string in the top row need translation to be enable as the strings that look like they are in Weblate are duplicated

![image](https://user-images.githubusercontent.com/17465872/161379895-b5da1c32-3a5e-4a0f-b476-dd44489cd46c.png)

Thank you

**Comment by danyeaw** [comment]
Closed by c17db2290f5e9832214a64a069d7d14c06229894

**Comment by ovari** [comment]
Can you please also allow:
4. [GitHub repository](https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?offset=1&q=GitHub+repository&sort_by=-priority%2Cposition&checksum=) top row popout string

`title='GitHub repository'`

https://github.com/gaphor/gaphor.github.io/commit/c17db2290f5e9832214a64a069d7d14c06229894#diff-2548bbc41e1f2e4846b6d5eda7fb961f5cc601fdae2a5dc2dbdf4e82d5634749R27

What do you think?

Thank you
