### ISSUE TITLE
`Download` heading on the main page (scroll down a bit)

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#57]
[Download](https://hosted.weblate.org/zen/gaphor/gaphor-github-io/hu/?offset=1&q=Download&sort_by=-priority%2Cposition&checksum=) heading on the main page (scroll down a bit)

![image](https://user-images.githubusercontent.com/17465872/161379964-5d1ad18f-1a7c-4bc8-b7ce-25361e0a1306.png)

Thank you

**Comment by danyeaw** [comment]
Closed by 0ff03b45af691b673466b942801090775a593cd6.
