### ISSUE TITLE
Footer translation

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#60]
[Theme](https://hosted.weblate.org/browse/gaphor/gaphor-github-io/hu/?offset=1&q=Theme&sort_by=-priority%2Cposition&checksum=) bottom footer

![image](https://user-images.githubusercontent.com/17465872/161380051-0a7b3eae-c0ca-45cb-a1d8-4814ac93e434.png)

Thank you

**Comment by danyeaw** [comment]
Closed by 49728c1b8f0948ec5f06dcfc09d7b62c2c013307.
