### ISSUE TITLE
Switching language returns to home page

### ISSUE THREAD

**Issue by milotype** [gaphor/gaphor.github.io#64]
Currently the website does not completely translate into defined languages. Some context translates, some of it doesn't.

Also, when changing the language of a certain web-page, switching languages always returns to the main web page (home-page) of the selected language. It should simply display the same page but in the other language.

For instance:
- go to "https://gaphor.org/"
- select "Download" (https://gaphor.org/download/)
- switch language to Croatian
- the website returns to the Croatian homepage "https://gaphor.org/hr/"

Same is true for Hungarian ...

**Comment by danyeaw** [comment]
Fixed by #108. Thanks for reporting this @milotype!
