### ISSUE TITLE
Website Build is Failing to Translate Large Portions

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#65]
![image](https://user-images.githubusercontent.com/17465872/162591155-fbbc0937-1ce4-45a2-981d-0fce32e36c97.png)

![image](https://user-images.githubusercontent.com/17465872/162591160-74989fd0-daa0-461c-a5ba-7006e2ee7ccf.png)

Thank you

**Comment by danyeaw** [comment]
@ovari Is there something that is translated not appearing on the website?

**Comment by ovari** [comment]
@danyeaw the image above shows the Croatian edition of the website. From the picture above there are lots of strings that are showing in English, not Croatian:
* A picture is ...
* Learn more
* Download

A bit lower down on the main page, all the strings are in English, as shown in the image below:
![image](https://user-images.githubusercontent.com/17465872/162591673-ebbcc73e-525a-4fb3-b318-681cee1d8fc3.png)

Further down the page, the image captions are also in English, as shown in the image below:
![image](https://user-images.githubusercontent.com/17465872/162591710-e6485aea-1e9c-4313-ba07-6fcc8965489e.png)

Near the bottom of the page, it seems that all the text is in English, not Croatian, as shown in the image below:
![image](https://user-images.githubusercontent.com/17465872/162591728-565efb8a-c2b2-4e1e-9efa-9779d8077ca7.png)

**Comment by ovari** [comment]
`A picture is worth a thousand words. Describe and document your applications and systems with Gaphor to enhance knowledge sharing.` has been translated into Hungarian some time ago and is not showing on https://gaphor.org/hu/

![image](https://user-images.githubusercontent.com/17465872/162610402-aecc6f3c-4973-42d6-9a1c-9d15b139ec39.png)

![image](https://user-images.githubusercontent.com/17465872/162610426-c7179d2b-d419-49da-9153-38a750395480.png)

Can you please push the translations for Hungarian too?

Thank you

**Comment by danyeaw** [comment]
Thanks for the bug report. This isn't just needing to rebuild, the website is failing to translate a lot of the strings. I'll have to look into this more.

**Comment by danyeaw** [comment]
I looked into this today. It looks like the `{% include content.md %}` markers automatically pull in `_include/content.md` instead of the `content.md` specific to the language. I need to figure out a workaround to pull in the correct translated files.

**Comment by milotype** [comment]
@danyeaw I'm sure you are busy with other and maybe more important issues, but it would be great if you (or some other programmer/contributor) could takle this issue and resolve it! :-) The issue is already one year old.

**Comment by danyeaw** [comment]
Thanks @milotype and @ovari for your patience on this one. This should now be all complete, maybe with a few tweaks needed here and there. Feel free to open additional issues if you run in to any issues.
