### ISSUE TITLE
Please enable translation of `UML/SysML Modeling` in top left of main webpage

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#66]
Please enable `UML/SysML Modeling` to be translatable. It is shown in the top left of the main webpage under the Gaphor image.

![image](https://user-images.githubusercontent.com/17465872/162610695-aa2ba5ca-94bc-4ecf-8b8b-33b61309dacd.png)

What do you think?

Thank you

**Comment by amolenaar** [comment]
Although this is in text, it's part of the logo as far as I'm concerned. The spacing has been adapted to fit the logo image. I like to leave this as is.
