### ISSUE TITLE
Should `About` be one written once, not twice?

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#70]
`About` is written twice at https://gaphor.org/, as shown in the image below:

![About](https://user-images.githubusercontent.com/17465872/163056362-ec753e92-ba1d-4a2e-9203-81fcd5d67e71.png)

Should `About` only be written once?

What do you think?

Thank you

**Comment by danyeaw** [comment]
I no longer see this on the website, and I think it is fixed.
