### ISSUE TITLE
Russian language support in fonts

### ISSUE THREAD

**Issue by BrainKicker** [gaphor/gaphor.github.io#92]
The site is currently using the Lato 1.0 font, which does not support the Russian language.

There are two solutions to this problem:
1) Use Lato 2.0 font;
2) Use a different font.

It seems that the first solution is much simpler and better.

Information about Lato: https://www.latofonts.com

And I also noticed that the font used for the title - Poppins - also does not support the Russian language. There is a font similar to it - Montserrat - it does.

**Comment by danyeaw** [comment]
Thanks @BrainKicker!

@amolenaar any thoughts on font selection?

**Comment by danyeaw** [comment]
It looks like Lato 2.0 is only available with the Adobe Typekit. It isn't a very exciting font, because it is so heavily used, but maybe we should just switch to Open Sans. It has full support for all languages.

**Comment by danyeaw** [comment]
@BrainKicker Is this still an issue, it looks like your translations are showing up at https://gaphor.org/ru/

**Comment by danyeaw** [comment]
This looks like it is fixed, please let us know if not.
